// <auto-generated />
namespace Integra.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class CorrecaoClinicaRemocaoRequeridoCampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorrecaoClinicaRemocaoRequeridoCampos));
        
        string IMigrationMetadata.Id
        {
            get { return "201307310210564_CorrecaoClinicaRemocaoRequeridoCampos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
