// <auto-generated />
namespace Integra.Repositorio.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdicionadoDataNaFatura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionadoDataNaFatura));
        
        string IMigrationMetadata.Id
        {
            get { return "201305290209166_AdicionadoDataNaFatura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
