// <auto-generated />
namespace Integra.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Clinica_column_Bairro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Clinica_column_Bairro));
        
        string IMigrationMetadata.Id
        {
            get { return "201403211121432_Clinica_column_Bairro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
