// <auto-generated />
namespace Integra.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class coluna_flag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coluna_flag));
        
        string IMigrationMetadata.Id
        {
            get { return "201402281655329_coluna_flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
