// <auto-generated />
namespace Integra.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Pagamento_Add_DataPagamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pagamento_Add_DataPagamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201403271509038_Pagamento_Add_DataPagamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
