// <auto-generated />
namespace Integra.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class add_coluna_nome_CRM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_coluna_nome_CRM));
        
        string IMigrationMetadata.Id
        {
            get { return "201403052020316_add_coluna_nome_CRM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
